// Oura Ring API v2 client.
// Docs: https://cloud.ouraring.com/v2/docs
// Auth: Personal Access Token (Bearer). Generated by the user at
//   https://cloud.ouraring.com/personal-access-tokens
//
// All date-based endpoints take start_date / end_date (YYYY-MM-DD).
// Time-series endpoints (heartrate) take start_datetime / end_datetime (ISO).

const BASE = 'https://api.ouraring.com/v2/usercollection';

export class OuraError extends Error {
  constructor(message, status) {
    super(message);
    this.name = 'OuraError';
    this.status = status;
  }
}

async function request(path, token, params = {}) {
  if (!token) throw new OuraError('No Oura access token set', 401);
  const qs = new URLSearchParams(params).toString();
  const url = `${BASE}/${path}${qs ? `?${qs}` : ''}`;

  let res;
  try {
    res = await fetch(url, {
      headers: { Authorization: `Bearer ${token}` },
    });
  } catch (e) {
    throw new OuraError(`Network error reaching Oura: ${e.message}`, 0);
  }

  if (res.status === 401) throw new OuraError('Invalid or expired Oura token', 401);
  if (res.status === 426)
    throw new OuraError('This data needs an active Oura membership', 426);
  if (res.status === 429) throw new OuraError('Oura rate limit hit — try again shortly', 429);
  if (!res.ok) {
    let detail = '';
    try {
      detail = JSON.stringify(await res.json());
    } catch {
      // ignore
    }
    throw new OuraError(`Oura request failed (${res.status}) ${detail}`, res.status);
  }
  return res.json();
}

// Paginates an Oura collection endpoint, following next_token until exhausted.
async function collection(path, token, params = {}) {
  let out = [];
  let next = null;
  let guard = 0;
  do {
    const page = await request(path, token, next ? { ...params, next_token: next } : params);
    out = out.concat(page.data || []);
    next = page.next_token;
    guard += 1;
  } while (next && guard < 20);
  return out;
}

export const oura = {
  // Quick validity check for onboarding.
  async verify(token) {
    const info = await request('personal_info', token);
    return info;
  },

  personalInfo: (token) => request('personal_info', token),

  dailySleep: (token, start, end) =>
    collection('daily_sleep', token, { start_date: start, end_date: end }),

  // Detailed per-period sleep documents (stages, hr, hrv, respiratory rate...).
  sleep: (token, start, end) =>
    collection('sleep', token, { start_date: start, end_date: end }),

  dailyReadiness: (token, start, end) =>
    collection('daily_readiness', token, { start_date: start, end_date: end }),

  dailyActivity: (token, start, end) =>
    collection('daily_activity', token, { start_date: start, end_date: end }),

  dailyStress: (token, start, end) =>
    collection('daily_stress', token, { start_date: start, end_date: end }),

  dailySpo2: (token, start, end) =>
    collection('daily_spo2', token, { start_date: start, end_date: end }),

  dailyResilience: (token, start, end) =>
    collection('daily_resilience', token, { start_date: start, end_date: end }),

  dailyCardiovascularAge: (token, start, end) =>
    collection('daily_cardiovascular_age', token, { start_date: start, end_date: end }),

  vo2max: (token, start, end) =>
    collection('vO2_max', token, { start_date: start, end_date: end }),

  workouts: (token, start, end) =>
    collection('workout', token, { start_date: start, end_date: end }),

  // Heart rate is a high-resolution time series.
  heartrate: (token, startDateTime, endDateTime) =>
    collection('heartrate', token, {
      start_datetime: startDateTime,
      end_datetime: endDateTime,
    }),
};
